// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsagUZpA9bMVAW4XXhptpyGGEKTlOtHYE',
    appId: '1:1059722601677:web:84ed511a31ce6c76537584',
    messagingSenderId: '1059722601677',
    projectId: 'nutrito-base',
    authDomain: 'nutrito-base.firebaseapp.com',
    storageBucket: 'nutrito-base.firebasestorage.app',
    measurementId: 'G-2LHM39VX63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAD7NAtC0KaLRaLq8abHjIT-1vNP0hyI',
    appId: '1:1059722601677:android:3332922422cefe35537584',
    messagingSenderId: '1059722601677',
    projectId: 'nutrito-base',
    storageBucket: 'nutrito-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zYW_WMFsJbBXrOW9Dv_xI0aYXiUNRtA',
    appId: '1:1059722601677:ios:f6c657ba2dca1734537584',
    messagingSenderId: '1059722601677',
    projectId: 'nutrito-base',
    storageBucket: 'nutrito-base.firebasestorage.app',
    iosBundleId: 'com.example.nutrito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zYW_WMFsJbBXrOW9Dv_xI0aYXiUNRtA',
    appId: '1:1059722601677:ios:f6c657ba2dca1734537584',
    messagingSenderId: '1059722601677',
    projectId: 'nutrito-base',
    storageBucket: 'nutrito-base.firebasestorage.app',
    iosBundleId: 'com.example.nutrito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsagUZpA9bMVAW4XXhptpyGGEKTlOtHYE',
    appId: '1:1059722601677:web:4e3d2fcad4a17345537584',
    messagingSenderId: '1059722601677',
    projectId: 'nutrito-base',
    authDomain: 'nutrito-base.firebaseapp.com',
    storageBucket: 'nutrito-base.firebasestorage.app',
    measurementId: 'G-YN9768C6N9',
  );
}
